name: bitcask tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: go test
      run: go test -v -cover ./...